import AuthProvider from './components/AuthProvider/page';
import { ContextProvider } from './QuizContext/page'
import './globals.css'

export const metadata = {
  title: 'SMIT - Quiz Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <AuthProvider>
      <html lang="en">
        <ContextProvider>
          <body>{children}</body>
        </ContextProvider>
      </html>
    </AuthProvider>
  )
}
