import AuthProvider from './components/AuthProvider/page';
import { ContextProvider } from '../QuizContext/page'
import './globals.css'
import Footer from './components/footer/page';

export const metadata = {
  title: 'SMIT - Quiz Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <AuthProvider>
      <html lang="en">
        <head>
          <link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
        </head>
        <ContextProvider>
          <body>
            {children}
          </body>
          <footer>
            <Footer />
          </footer>
        </ContextProvider>
      </html>
    </AuthProvider>
  )
}

